server:
  port: 8089

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://111.231.74.19:3306/mwtutu
        driver-class-name: com.mysql.jdbc.Driver
        username: xuyong
        password: liuyao

# mybatis 配置
mybatis:
    mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.mwtutu.domain  # 注意：对应实体类的路径
    mappers: com.mwtutu.utils.MyMapper
    not-empty: false
    identity: MYSQL

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#MongoDB
mongodb:
    addresses: 111.231.74.19:27017
    username: xuyong
    password: 123456
    admindb: mwtutu
    database: mwtutu